### ISSUE TITLE
[FEAT] Write numpy code for ranking function

### ISSUE THREAD

**Issue by WizzyGeek** [WizzyGeek/GAMS#1]
https://github.com/WizzyGeek/GAMS/blob/4fac72925bde2d0d6f6830387169ddc0927bdc4f/GAMS/ranker.py#L13

Write the equivalent working numpy code for the function

**Comment by Microturbine** [comment]
I am a beginner but would like to make a few modifications as a learning experience.
I wrote the numpy function as described.
I will send you a pull request so you can take a look if you like.
